[package]
name = "sted"
version = "0.1.0"
authors = ["Austin Bingham <austin.bingham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.30.10"
num = "0.4.3"
float-cmp = "0.10.0"
