[package]
name = "roid-rage-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.14.2"
prost = "0.14.3"
prost-types = "0.14.3"
tonic-prost = "0.14.2"
sted = {path = "../sted"}
glam = "0.30.10"

[build-dependencies]
tonic-prost-build = "0.14.2"
